redis:
  image: redis:3.2-alpine
  ports:
   - "6379:6379"
fuseki:
  build: ../sevi-docker-fuseki-public
  ports:
   - "3030:3030"
  command: --config=/jena-fuseki/config.ttl
activemq:
  build: ../sevi-docker-activemq-public
  ports:
   - "8161:8161"
   - "61616:61616"
ontologyservice:
  image: sevi/sevi-ontology-service:latest
  ports:
   - "9089:9089"
   - "19089:19089"
  volumes:
   - ../sevi-config-public:/config
  command: -j -Xmx512M -a --spring.config.location=/config/application.yml,/config/sevi-ontology-service.yml
  links:
   - activemq
   - fuseki
   - redis

